// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5qpmgUmpEiEOo0Tgp6dt6RUK8CtE4VIg',
    appId: '1:287482928261:web:096bf2be948648b65eddec',
    messagingSenderId: '287482928261',
    projectId: 'expensetrackerapp-a2b32',
    authDomain: 'expensetrackerapp-a2b32.firebaseapp.com',
    storageBucket: 'expensetrackerapp-a2b32.firebasestorage.app',
    measurementId: 'G-2BYR0SEQPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhHNOMhjA7-05Ck1isXPA9SpbykTZKm3c',
    appId: '1:287482928261:android:069fdb8737091f515eddec',
    messagingSenderId: '287482928261',
    projectId: 'expensetrackerapp-a2b32',
    storageBucket: 'expensetrackerapp-a2b32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaVCKLlIANY8LBruf61eopsqIMViW7z2w',
    appId: '1:287482928261:ios:4d6a155d1cb96a2d5eddec',
    messagingSenderId: '287482928261',
    projectId: 'expensetrackerapp-a2b32',
    storageBucket: 'expensetrackerapp-a2b32.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaVCKLlIANY8LBruf61eopsqIMViW7z2w',
    appId: '1:287482928261:ios:4d6a155d1cb96a2d5eddec',
    messagingSenderId: '287482928261',
    projectId: 'expensetrackerapp-a2b32',
    storageBucket: 'expensetrackerapp-a2b32.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5qpmgUmpEiEOo0Tgp6dt6RUK8CtE4VIg',
    appId: '1:287482928261:web:a962e9f6c704c8055eddec',
    messagingSenderId: '287482928261',
    projectId: 'expensetrackerapp-a2b32',
    authDomain: 'expensetrackerapp-a2b32.firebaseapp.com',
    storageBucket: 'expensetrackerapp-a2b32.firebasestorage.app',
    measurementId: 'G-F55G0WYG62',
  );
}
