name: expense_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^2.0.0
  lottie: ^2.3.2
  animated_splash_screen : ^1.2.0
    

  # UI and Charts
  google_fonts: ^6.1.0
  fl_chart: ^1.0.0
  http: ^1.4.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.2

  image_picker: ^1.0.7
  csv: ^5.0.2
  share_plus: ^7.2.1
  path_provider: ^2.1.2
  url_launcher: ^6.2.5
  permission_handler: ^11.0.1
  

  

  # ✅ Updated Firebase packages to compatible versions
  firebase_core: ^3.13.1
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  google_sign_in: ^6.2.1
  firebase_ui_oauth_google: ^1.2.12

  # ✅ Compatible Firebase UI version
  firebase_ui_auth: ^1.16.1
  firebase_ui_firestore: ^1.6.0
  firebase_ui_storage: ^2.1.1

  flutter_local_notifications: ^16.1.0
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/animation/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/font/Inter-Regular.ttf
        - asset: assets/font/Inter-Medium.ttf
          weight: 500
        - asset: assets/font/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/font/Inter-Bold.ttf
          weight: 700
